import type { Metadata } from "next";
import { Inter, Cause } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { AuthShell } from "@/components/auth-shell";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const autoMoney = Cause({
  variable: "--font-auto-money",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Auto Money",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${autoMoney.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-background">
        <Providers>
          <AuthShell>{children}</AuthShell>
        </Providers>
      </body>
    </html>
  );
}
